version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000

  celery_worker:
    build: .
    command: celery_worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - server
      - redis

  celery_beat:
    build: .
    command: celery_beat
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - server
      - redis

  redis:
    image: redis:5.0-alpine
    command: --port 6379
    restart: unless-stopped
    ports:
      - "127.0.0.1:6391:6379"
    volumes:
      - ./redis:/data

  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:13309:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: password@2019
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    restart: unless-stopped
